.github/workflows/keccak.yml

`packed_simd_2` no longer builds on nightly:
https://github.com/rust-lang/packed_simd/issues/343
This commit pins the nightly version for now, and disables the `minimal-versions` check since it's not customizable and requires the latest nightly.

keccak: fix build

---

keccak/CHANGELOG.md
keccak/Cargo.toml

- Generic keccak-p and keccak-f {200, 400, 800} ([#7])
- f1600x{2, 4, 8} ([#8])
[#7]: https://github.com/RustCrypto/sponges/pull/7
[#8]: https://github.com/RustCrypto/sponges/pull/8

keccak v0.1.1

---

.github/workflows/keccak.yml
keccak/Cargo.toml
keccak/benches/mod.rs
keccak/src/lib.rs

@tarcieri I just migrated to use portable_simd.
EDIT: Just force-pushed to remove an unnecessary change, which I didnot spot before.

Use portable_simd instead of deprecate packed_simd

---

keccak/CHANGELOG.md
keccak/Cargo.toml
keccak/README.md

- Implement `simd` feature with  `portable_simd` instead of deprecated `packed_simd` ([#16])
[#16]: https://github.com/RustCrypto/sponges/pull/16

keccak v0.1.2

---

.github/actions/cross-tests/action.yml
.github/workflows/keccak.yml
.github/workflows/security-audit.yml
.github/workflows/workspace.yml

Updates the actions [`actions/checkout`](https://github.com/actions/checkout) and [`actions/cache`](https://github.com/actions/cache) to v3, their latest major release.
This should basically be backwards compatible, so I expect no breakage.

Update actions used in GitHub Actions workflows to newest version

---

.github/workflows/keccak.yml
keccak/src/aarch64_sha3.rs
keccak/src/lib.rs

This uses ARMv8.4-A FEAT_SHA3 instructions which can be found on recent Apple processors. (tested on M1, but ARMv8.4 is as early as A13, but I can't find information if A13 implements the SHA3 extensions)

Add aarch64 asm implementation keccak_f1600

---

keccak/Cargo.toml
keccak/src/aarch64_sha3.rs
keccak/src/lib.rs

Gates `asm` support under a crate feature.
Uses the `cpufeatures` crate to detect the presence of the `sha3` extension for ARMv8 CPUs, automatically falling back to a software implementation if it isn't available.
cc @recmo

keccak: add `asm` feature; use `cpufeatures` on `aarch64`

---

keccak/README.md
keccak/src/armv8.rs
keccak/src/lib.rs

Include the target architecture and feature in the name of the function.

keccak: rename `f1600_armv8_sha3_asm`

---

keccak/Cargo.toml
keccak/src/armv8.rs
keccak/src/lib.rs
keccak/src/unroll.rs

- Bumps the crate's edition to 2018, which is MSRV-compatible.
- Adds a more expansive set of lints
- Adds the `missing_docs` lint, and adds docs where missing
- Fixes tests on ARMv8

keccak: 2018 edition upgrade, lints, docs

---

Cargo.lock
ascon/Cargo.toml
ascon/README.md
ascon/src/lib.rs
ascon/src/ops.rs

- Bumps the crate's edition to 2018, which is MSRV-compatible
- Adds a more expansive set of lints
- Adds the `missing_docs` lint, and adds docs where missing

ascon: 2018 edition upgrade, lints, docs

---

.github/workflows/ascon.yml
ascon/Cargo.toml
ascon/src/aead.rs
ascon/src/lib.rs
ascon/src/util.rs

The permutation does not have any `std`/`alloc` dependency.
The current AEAD interface requires `alloc` (though we should migrate it to use the `aead` crate anyway).

ascon: add `no_std` support

---

Cargo.lock
ascon/Cargo.toml
ascon/src/lib.rs
ascon/src/util.rs

We can use the support in `core` instead

ascon: remove `byteorder` dependency

---

.github/workflows/ascon.yml
ascon/README.md
ascon/src/aead.rs
ascon/src/lib.rs

Adds a struct which wraps the permutation state, using const generics as well as `feature(const_generics_defaults)` to express the `A`/`B` parameters for `Ascon(a,b)`.

ascon: extract `Ascon` permutation type; MSRV 1.59

---

ascon/Cargo.toml
ascon/src/lib.rs

Since #39 bumped MSRV to 1.59, we can go ahead and do a 2021 edition upgrade, including README.md in the toplevel rustdoc.

ascon: 2021 edition

---

Cargo.toml
keccak/Cargo.lock

The build is failing because `keccak` has a very old MSRV of 1.41, which after merging #40 (which bumped the `ascon` edition to 2021) broke the build because it can't handle the `edition` key.
As a workaround, this excludes `keccak` from the toplevel workspace so it doesn't try to read the `ascon` edition key.
Separately, we should probably bump the `keccak` edition to 2021 as well and release `keccak` v0.2.0, but that is left for future work.

CI: exclude `keccak` from toplevel workspace

---

Cargo.lock
ascon/src/aead.rs
ascon/src/lib.rs

- Adds a type alias for Ascon keys (16-byte)
- Stores key internally in `struct Ascon` so it doesn't need to be passed separately to `Ascon::finalize`.

ascon: `Key` type alias; cache key in `Ascon` state

---

ascon/src/aead.rs
ascon/src/lib.rs

Adds a type alias for Ascon nonces, set to `[u8; 16]`.
From the Ascon paper section 2.4:
https://link.springer.com/article/10.1007/s00145-021-09398-9
> The 320-bit initial state of Ascon is formed by the secret key K of
> k bits and nonce N of 128 bits

ascon: add `Nonce` type alias

---

.github/workflows/ascon.yml
Cargo.lock
ascon/Cargo.toml
ascon/LICENSE-APACHE
ascon/README.md
ascon/benches/bench.rs
ascon/src/aead.rs
ascon/src/lib.rs

Impls the standard AEAD API from the `aead` crate.
Eventually we can split this API out into a separate crate, e.g. `ascon-aead`, but for now this just gets things working initially.
Uses weak/namespaced features which requires MSRV 1.60.

ascon: use `aead` crate for AEAD API; MSRV 1.60

---

Cargo.lock
ascon/CHANGELOG.md
ascon/Cargo.toml
ascon/README.md

-  `no_std` support ([#36])
- `Ascon` permutation type ([#39])
- `Key` type alias ([#42])
- `Nonce` type alias ([#43])
- 2021 edition ([#40])
- Use `aead` crate for AEAD API ([#44])
- MSRV 1.60 ([#44])
- `byteorder` dependency ([#37])
[#36]: https://github.com/RustCrypto/sponges/pull/36
[#37]: https://github.com/RustCrypto/sponges/pull/37
[#39]: https://github.com/RustCrypto/sponges/pull/39
[#40]: https://github.com/RustCrypto/sponges/pull/40
[#42]: https://github.com/RustCrypto/sponges/pull/42
[#43]: https://github.com/RustCrypto/sponges/pull/43
[#44]: https://github.com/RustCrypto/sponges/pull/44

ascon v0.2.0

---

.github/workflows/ascon.yml
Cargo.lock
ascon/Cargo.toml
ascon/README.md
ascon/src/lib.rs

MSRV was raised for `ascon` in c8b07a46c86b240d3ce9c5e75a4f23117a874e19. After the merge of `ascon-core`, 1.56 provides all required features.

ascon: drop MSRV to 1.56

---

.github/actions/cross-tests/action.yml
.github/workflows/ascon.yml
.github/workflows/keccak.yml
.github/workflows/workspace.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/sponges/actions/runs/4461461361:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations of …

Replace unmaintained actions-rs/* actions in CI workflows

---

keccak/src/lib.rs

Due to the generics approach of the keccak_p routine, the performance degrades significantly. To encounter this the commonly used functions are now defined by macros.
See https://github.com/RustCrypto/hashes/issues/468 for issue raised about performance degradation.

keccak: Add keccak_p fns for [200, 400, 800, 1600]

---

keccak/CHANGELOG.md
keccak/Cargo.lock
keccak/Cargo.toml

- `keccak_p` fns for `[200, 400, 800, 1600]` ([#55])
- 2018 edition upgrade ([#32])
[#32]: https://github.com/RustCrypto/sponges/pull/32
[#55]: https://github.com/RustCrypto/sponges/pull/55

keccak v0.1.4

---

.github/workflows/keccak.yml

`mips-unknown-linux-gnu` is now a Tier 3 target: rust-lang/rust#115218.
This means we can't use it for cross tests anymore since std is no longer built for it.
This commit replaces it with `powerpc-unknown-linux-gnu`, a big endian Tier 2 target.

keccak: replace CI tests on MIPS with PPC32

---

.github/workflows/keccak.yml

It requires `nightly`, whereas the tests are run under `stable`.
The `simd` feature itself is already tested in the `test-simd` job.

keccak: don't test `simd` feature in `minimal-versions` workflow

---

Cargo.lock

This reverts commit 3a9a29ef77f4718b6a385d08779d098dded51ef7.
This update is higher than the current Ascon MSRV and broke the build

Revert "Update Cargo.lock"

---

keccak/benches/mod.rs
keccak/src/armv8.rs
keccak/src/lib.rs

Enable the use of the aarch64 assembly backend for `p1600` in addition to `f1600`.
Before:
```text
test b_p1600_16 ... bench:         142 ns/iter (+/- 9)
test b_p1600_24 ... bench:         211 ns/iter (+/- 3)
```
After:
```text
test b_p1600_16 ... bench:          95 ns/iter (+/- 2)
test b_p1600_24 ... bench:         141 ns/iter (+/- 3)
```

keccak: enable asm backend for p1600

---

keccak/CHANGELOG.md
keccak/Cargo.lock
keccak/Cargo.toml

- Enable ARMv8 ASM backend for `p1600` ([#68])
[#68]: https://github.com/RustCrypto/sponges/pull/68

keccak v0.1.5

---

Cargo.lock

This is possible now that we've bumped `ascon`'s MSRV to 1.60

Cargo.lock: bump `zeroize` to v1.8.1

---

ascon/Cargo.toml
keccak/Cargo.toml

This tweaks the `repository` fields in Cargo metadata in order to use the correct (i.e. git clonable) URL. The existing GitHub webUI URLs for each package have been retained and moved to `homepage` fields.

cargo: point `repository` metadata to clonable URLs

---

keccak/src/lib.rs

`t1` and `t2` in the second step of Theta phase can be computed outside of the y loop as they rely only on x.

keccak_p: improve efficiency of Theta phase

---

.github/workflows/ascon.yml
.github/workflows/keccak.yml
.github/workflows/workspace.yml
ascon/Cargo.toml
ascon/README.md
keccak/Cargo.toml
keccak/README.md
keccak/src/lib.rs

1.81 is the new MSRV baseline for our downstream crates, so I think we can have a similar MSRV bump for these crates as well despite the fact that they technically can work with older Rust versions. This also should future-proof as a bit against potential bumps in `libc` which recently has bumped MSRV to 1.63.

Bump MSRV to 1.81

---

keccak/src/lib.rs

See https://github.com/rust-lang/rust/pull/138907

Use doc_cfg in place of removed doc_auto_cfg feature.
